### ISSUE TITLE
Sparkles should not take mouse interaction, so the buttons can be clicked

### ISSUE THREAD

**Issue by cloudrac3r** [SaraVieira/human-blahaj#1]
Nice site :sparkles::shark:

I'm pretty sure this CSS should do the trick for making objects clickable through sparkles:

```
.sparkle-container {
   pointer-events: none;
}
```

**Comment by SaraVieira** [comment]
It worked! :D

Thank you

**Comment by SaraVieira** [comment]
Fix is live :)
